if(NOT DEFINED GBB_RUNNER OR NOT DEFINED GBB_MANIFEST OR NOT DEFINED GBB_MODE)
  message(FATAL_ERROR "runner negative control is missing an input")
endif()
if(GBB_MODE STREQUAL "missing")
  execute_process(COMMAND "${GBB_RUNNER}" --manifest "${GBB_MANIFEST}" --case daa --receipt
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  set(expected "eligible=1 executed=0")
elseif(GBB_MODE STREQUAL "manifest")
  execute_process(COMMAND "${GBB_RUNNER}" --manifest "${GBB_MANIFEST}" --suite
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  set(expected "invalid-manifest")
elseif(GBB_MODE STREQUAL "digest")
  execute_process(COMMAND "${GBB_RUNNER}" --manifest "${GBB_MANIFEST}" --case daa --receipt
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  set(expected "missing-or-invalid-fixture.*eligible=1 executed=0")
else()
  message(FATAL_ERROR "unknown runner negative control")
endif()
if(result STREQUAL "0" OR result MATCHES "^-1$")
  message(FATAL_ERROR "runner unexpectedly succeeded; output: ${output}${error}")
endif()
set(combined "${output}${error}")
if(NOT combined MATCHES "${expected}")
  message(FATAL_ERROR "runner failed for the wrong reason; expected ${expected}; output: ${combined}")
endif()
