foreach(required IN ITEMS GBB_RECEIPT GBB_ASSET GBB_NOTICE_FILE GBB_EXPECTED_VERSION GBB_EXPECTED_TAG GBB_EXPECTED_SOURCE_SHA GBB_EXPECTED_RELEASE_ID)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

if(NOT EXISTS "${GBB_RECEIPT}" OR NOT EXISTS "${GBB_ASSET}")
  message(FATAL_ERROR "Release receipt or candidate asset is missing")
endif()
string(LENGTH "${GBB_EXPECTED_SOURCE_SHA}" expected_sha_length)
if(NOT expected_sha_length EQUAL 40 OR NOT GBB_EXPECTED_SOURCE_SHA MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Expected source SHA must be a lowercase full 40-character commit ID")
endif()
if(NOT GBB_EXPECTED_TAG STREQUAL "v${GBB_EXPECTED_VERSION}")
  message(FATAL_ERROR "Expected tag does not match the CMake project version")
endif()

file(READ "${GBB_RECEIPT}" receipt)
string(JSON schema ERROR_VARIABLE error GET "${receipt}" schema_version)
if(NOT error STREQUAL "NOTFOUND" OR NOT schema EQUAL 1)
  message(FATAL_ERROR "Release receipt schema_version must be 1")
endif()
foreach(field IN ITEMS version tag_name source_sha release_id draft source_clean smoke_result notice_file release_notes)
  string(JSON value ERROR_VARIABLE error GET "${receipt}" ${field})
  if(NOT error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Release receipt is missing valid ${field}: ${error}")
  endif()
  set(receipt_${field} "${value}")
endforeach()
if(NOT receipt_version STREQUAL GBB_EXPECTED_VERSION OR NOT receipt_tag_name STREQUAL GBB_EXPECTED_TAG)
  message(FATAL_ERROR "Release receipt version/tag does not match the expected CMake version")
endif()
if(NOT receipt_source_sha STREQUAL GBB_EXPECTED_SOURCE_SHA)
  message(FATAL_ERROR "Release receipt source SHA differs from the trusted tag")
endif()
if(NOT receipt_release_id STREQUAL GBB_EXPECTED_RELEASE_ID)
  message(FATAL_ERROR "Release receipt release ID does not identify the sole existing draft")
endif()
if(NOT receipt_draft)
  message(FATAL_ERROR "Candidate release is published or draft state is missing")
endif()
if(NOT receipt_source_clean)
  message(FATAL_ERROR "Candidate source checkout was not clean")
endif()
if(NOT receipt_smoke_result STREQUAL "passed")
  message(FATAL_ERROR "Downloaded-byte consumer smoke did not pass")
endif()
if(NOT receipt_notice_file STREQUAL "gabbaboy-notices.txt" OR NOT EXISTS "${GBB_NOTICE_FILE}")
  message(FATAL_ERROR "Release notices are missing or have an unexpected asset name")
endif()
string(JSON notice_sha ERROR_VARIABLE error GET "${receipt}" notice_sha256)
if(NOT error STREQUAL "NOTFOUND" OR NOT notice_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Release notice SHA-256 is missing or malformed")
endif()
string(LENGTH "${notice_sha}" notice_sha_length)
if(NOT notice_sha_length EQUAL 64)
  message(FATAL_ERROR "Release notice SHA-256 must contain 64 characters")
endif()
file(SHA256 "${GBB_NOTICE_FILE}" actual_notice_sha)
if(NOT actual_notice_sha STREQUAL notice_sha)
  message(FATAL_ERROR "Release notice bytes do not match the receipt")
endif()
if(receipt_release_notes STREQUAL "")
  message(FATAL_ERROR "Release notes are missing")
endif()
string(JSON release_notes_sha ERROR_VARIABLE error GET "${receipt}" release_notes_sha256)
if(NOT error STREQUAL "NOTFOUND" OR NOT release_notes_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Release notes SHA-256 is missing or malformed")
endif()
string(LENGTH "${release_notes_sha}" release_notes_sha_length)
if(NOT release_notes_sha_length EQUAL 64)
  message(FATAL_ERROR "Release notes SHA-256 must contain 64 characters")
endif()
string(SHA256 actual_release_notes_sha "${receipt_release_notes}")
if(NOT actual_release_notes_sha STREQUAL release_notes_sha)
  message(FATAL_ERROR "Release notes do not match their recorded digest")
endif()

foreach(field IN ITEMS compiler cmake runner configuration fixture_manifest_sha256 corpus_manifest_sha256)
  string(JSON value ERROR_VARIABLE error GET "${receipt}" build ${field})
  if(NOT error STREQUAL "NOTFOUND" OR value STREQUAL "")
    message(FATAL_ERROR "Release receipt build.${field} is missing")
  endif()
endforeach()
string(JSON fixture_sha ERROR_VARIABLE error GET "${receipt}" fixtures tracer_manifest_sha256)
if(NOT error STREQUAL "NOTFOUND" OR NOT fixture_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Tracer fixture manifest SHA-256 is malformed")
endif()
string(LENGTH "${fixture_sha}" fixture_sha_length)
if(NOT fixture_sha_length EQUAL 64)
  message(FATAL_ERROR "Tracer fixture manifest SHA-256 must contain 64 characters")
endif()
string(JSON battery_sha ERROR_VARIABLE error GET "${receipt}" fixtures battery_manifest_sha256)
if(NOT error STREQUAL "NOTFOUND" OR NOT battery_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Battery fixture manifest SHA-256 is malformed")
endif()
string(LENGTH "${battery_sha}" battery_sha_length)
if(NOT battery_sha_length EQUAL 64)
  message(FATAL_ERROR "Battery fixture manifest SHA-256 must contain 64 characters")
endif()
string(JSON build_fixture_sha GET "${receipt}" build fixture_manifest_sha256)
string(JSON build_corpus_sha GET "${receipt}" build corpus_manifest_sha256)
if(NOT build_fixture_sha STREQUAL fixture_sha OR NOT build_corpus_sha STREQUAL battery_sha)
  message(FATAL_ERROR "Build receipt fixture/corpus identities disagree with fixture metadata")
endif()
string(JSON asset_count ERROR_VARIABLE error LENGTH "${receipt}" assets)
if(NOT error STREQUAL "NOTFOUND" OR NOT asset_count EQUAL 1)
  message(FATAL_ERROR "Candidate receipt must contain exactly one core archive asset")
endif()
string(JSON asset_name ERROR_VARIABLE error GET "${receipt}" assets 0 name)
if(NOT error STREQUAL "NOTFOUND" OR NOT asset_name STREQUAL "gabbaboy-core-linux-x64.tar.gz")
  message(FATAL_ERROR "Candidate asset name is missing, unexpected, or duplicated")
endif()
string(JSON recorded_sha ERROR_VARIABLE error GET "${receipt}" assets 0 sha256)
if(NOT error STREQUAL "NOTFOUND" OR NOT recorded_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Candidate asset SHA-256 is missing or malformed")
endif()
string(LENGTH "${recorded_sha}" recorded_sha_length)
if(NOT recorded_sha_length EQUAL 64)
  message(FATAL_ERROR "Candidate asset SHA-256 must contain 64 characters")
endif()
file(SHA256 "${GBB_ASSET}" actual_sha)
if(NOT actual_sha STREQUAL recorded_sha)
  message(FATAL_ERROR "Downloaded candidate asset SHA-256 mismatch")
endif()

string(JSON proof_head_sha ERROR_VARIABLE error GET "${receipt}" prior_pr_proof head_sha)
if(NOT error STREQUAL "NOTFOUND" OR NOT proof_head_sha MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Candidate lacks a full exact-head PR proof SHA")
endif()
string(LENGTH "${proof_head_sha}" proof_head_sha_length)
if(NOT proof_head_sha_length EQUAL 40)
  message(FATAL_ERROR "Candidate PR proof SHA must contain 40 characters")
endif()
string(JSON proof_merge_sha ERROR_VARIABLE error GET "${receipt}" prior_pr_proof merge_commit_sha)
if(NOT error STREQUAL "NOTFOUND" OR NOT proof_merge_sha STREQUAL GBB_EXPECTED_SOURCE_SHA)
  message(FATAL_ERROR "Candidate lacks prior exact-head PR proof for the tagged merge commit")
endif()
string(JSON proof_status ERROR_VARIABLE error GET "${receipt}" prior_pr_proof required_checks)
if(NOT error STREQUAL "NOTFOUND" OR NOT proof_status STREQUAL "passed")
  message(FATAL_ERROR "Candidate prior exact-head required checks are absent or non-passing")
endif()

message(STATUS "Release receipt qualifies ${GBB_EXPECTED_TAG} at ${GBB_EXPECTED_SOURCE_SHA}; downloaded bytes match and smoke passed")
