if(NOT DEFINED ROM OR NOT DEFINED MANIFEST)
  message(FATAL_ERROR "ROM and MANIFEST paths are required")
endif()
if(NOT EXISTS "${ROM}" OR NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "Fixture ROM or manifest does not exist")
endif()

file(SHA256 "${ROM}" actual_sha256)
file(READ "${MANIFEST}" manifest_json)
string(JSON expected_sha256 ERROR_VARIABLE json_error GET "${manifest_json}" sha256)
if(NOT json_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Manifest sha256 is missing or invalid: ${json_error}")
endif()
string(TOLOWER "${expected_sha256}" expected_sha256)
if(NOT actual_sha256 STREQUAL expected_sha256)
  message(FATAL_ERROR "Fixture digest mismatch: expected ${expected_sha256}, got ${actual_sha256}")
endif()
message(STATUS "Verified tracer ROM SHA-256 ${actual_sha256}")
