if(NOT DEFINED GBB_MOONEYE_DIR)
  message(FATAL_ERROR "GBB_MOONEYE_DIR is required")
endif()

cmake_path(ABSOLUTE_PATH GBB_MOONEYE_DIR
  BASE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.." NORMALIZE OUTPUT_VARIABLE fixture_dir)
set(manifest_path "${fixture_dir}/manifest.json")
foreach(required_file IN ITEMS manifest.json LICENSE.txt FONT-LICENSE.txt SOURCES.md)
  if(NOT EXISTS "${fixture_dir}/${required_file}")
    message(FATAL_ERROR "Missing required Mooneye corpus file: ${required_file}")
  endif()
endforeach()

file(READ "${manifest_path}" manifest_json)
string(JSON fixture_count ERROR_VARIABLE json_error LENGTH "${manifest_json}" fixtures)
if(NOT json_error STREQUAL "NOTFOUND" OR fixture_count LESS 1)
  message(FATAL_ERROR "Manifest fixtures must be a non-empty JSON array: ${json_error}")
endif()
string(JSON inventory_status ERROR_VARIABLE json_error GET "${manifest_json}" inventory_status)
if(NOT json_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Manifest inventory_status is missing: ${json_error}")
endif()
if(NOT inventory_status STREQUAL "cpu-only-in-progress" AND
   NOT inventory_status STREQUAL "complete")
  message(FATAL_ERROR "Invalid manifest inventory_status: ${inventory_status}")
endif()

string(JSON required_count ERROR_VARIABLE json_error LENGTH "${manifest_json}" required_roms)
if(NOT json_error STREQUAL "NOTFOUND" OR required_count LESS 1)
  message(FATAL_ERROR "Manifest required_roms must be a non-empty array")
endif()
set(required_roms "")
foreach(index RANGE 0 ${required_count})
  if(index EQUAL required_count)
    break()
  endif()
  string(JSON required_rom ERROR_VARIABLE json_error GET "${manifest_json}" required_roms ${index})
  if(NOT json_error STREQUAL "NOTFOUND" OR required_rom MATCHES "[/\\\\]|\\.\\.")
    message(FATAL_ERROR "Invalid required ROM path at index ${index}: ${required_rom}")
  endif()
  list(APPEND required_roms "${required_rom}")
endforeach()
string(JSON excluded_count ERROR_VARIABLE json_error LENGTH "${manifest_json}" excluded_candidates)
if(NOT json_error STREQUAL "NOTFOUND" OR excluded_count LESS 1)
  message(FATAL_ERROR "Manifest must retain reviewed source-based exclusions")
endif()
foreach(index RANGE 0 ${excluded_count})
  if(index EQUAL excluded_count)
    break()
  endif()
  foreach(field IN ITEMS source_path reason)
    string(JSON exclusion_value ERROR_VARIABLE json_error GET "${manifest_json}" excluded_candidates ${index} ${field})
    if(NOT json_error STREQUAL "NOTFOUND" OR exclusion_value STREQUAL "")
      message(FATAL_ERROR "Exclusion ${index} has no ${field} evidence")
    endif()
  endforeach()
endforeach()

set(seen_ids "")
set(seen_roms "")
set(cpu_count 0)
set(timer_count 0)
foreach(index RANGE 0 ${fixture_count})
  if(index EQUAL fixture_count)
    break()
  endif()
  string(JSON id ERROR_VARIABLE json_error GET "${manifest_json}" fixtures ${index} id)
  if(NOT json_error STREQUAL "NOTFOUND" OR id STREQUAL "" OR id IN_LIST seen_ids)
    message(FATAL_ERROR "Missing or duplicate fixture id at index ${index}: ${id}")
  endif()
  list(APPEND seen_ids "${id}")

  string(JSON eligible ERROR_VARIABLE json_error GET "${manifest_json}" fixtures ${index} eligible)
  if(NOT json_error STREQUAL "NOTFOUND" OR NOT eligible)
    message(FATAL_ERROR "Every entry in fixtures must be source-qualified and eligible: ${id}")
  endif()
  string(JSON category ERROR_VARIABLE json_error GET "${manifest_json}" fixtures ${index} category)
  if(NOT json_error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Missing category for ${id}")
  elseif(category STREQUAL "cpu")
    math(EXPR cpu_count "${cpu_count} + 1")
  elseif(category STREQUAL "timer")
    math(EXPR timer_count "${timer_count} + 1")
  else()
    message(FATAL_ERROR "Unsupported eligible category '${category}' for ${id}")
  endif()

  foreach(field IN ITEMS source_path rom sha256 size_bytes license asset_notice model boot
                         oracle_class protocol timeout_half_dots build_recipe source_closure)
    string(JSON field_value ERROR_VARIABLE json_error GET "${manifest_json}" fixtures ${index} ${field})
    if(NOT json_error STREQUAL "NOTFOUND" OR field_value STREQUAL "")
      message(FATAL_ERROR "Missing required '${field}' metadata for ${id}: ${json_error}")
    endif()
  endforeach()
  string(JSON model GET "${manifest_json}" fixtures ${index} model)
  if(NOT model STREQUAL "DMG-CPU-B")
    message(FATAL_ERROR "Fixture ${id} is outside the declared DMG-CPU-B model")
  endif()
  string(JSON timeout_ticks GET "${manifest_json}" fixtures ${index} timeout_half_dots)
  if(NOT timeout_ticks MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "Fixture ${id} has no finite positive half-dot budget")
  endif()
  string(JSON rom GET "${manifest_json}" fixtures ${index} rom)
  if(rom MATCHES "[/\\\\]|\\.\\.")
    message(FATAL_ERROR "Fixture ROM must be a local filename: ${rom}")
  endif()
  string(JSON digest GET "${manifest_json}" fixtures ${index} sha256)
  string(JSON expected_size GET "${manifest_json}" fixtures ${index} size_bytes)
  string(LENGTH "${digest}" digest_length)
  if(NOT digest MATCHES "^[0-9a-fA-F]+$" OR NOT digest_length EQUAL 64 OR
     NOT expected_size MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "Fixture ${id} has malformed size or SHA-256 metadata")
  endif()
  set(rom_path "${fixture_dir}/${rom}")
  if(NOT EXISTS "${rom_path}")
    message(FATAL_ERROR "Missing required selected ROM: ${rom_path}")
  endif()
  file(SIZE "${rom_path}" actual_size)
  file(SHA256 "${rom_path}" actual_digest)
  if(NOT actual_size EQUAL expected_size OR NOT actual_digest STREQUAL digest)
    message(FATAL_ERROR "Fixture ${id} mismatch: size ${actual_size}/${expected_size}, SHA-256 ${actual_digest}/${digest}")
  endif()
  if(rom IN_LIST seen_roms)
    message(FATAL_ERROR "Duplicate ROM path in eligible inventory: ${rom}")
  endif()
  list(APPEND seen_roms "${rom}")
endforeach()

foreach(rom IN LISTS required_roms)
  if(NOT rom IN_LIST seen_roms)
    message(FATAL_ERROR "Required ROM is not represented in eligible manifest: ${rom}")
  endif()
endforeach()
if(NOT inventory_status STREQUAL "cpu-only-in-progress")
  if(cpu_count LESS 1 OR timer_count LESS 1)
    message(FATAL_ERROR "Complete eligible inventory requires at least one CPU and one timer fixture")
  endif()
  if(NOT seen_roms STREQUAL required_roms)
    message(FATAL_ERROR "required_roms must exactly match the eligible checked-in ROM paths")
  endif()
endif()

string(JSON replacement_path GET "${manifest_json}" replacement_asset path)
string(JSON replacement_sha GET "${manifest_json}" replacement_asset sha256)
string(JSON replacement_size GET "${manifest_json}" replacement_asset size_bytes)
string(LENGTH "${replacement_sha}" replacement_sha_length)
if(NOT replacement_path STREQUAL "font.bin" OR
   NOT replacement_sha MATCHES "^[0-9a-fA-F]+$" OR NOT replacement_sha_length EQUAL 64 OR
   NOT replacement_size EQUAL 2032)
  message(FATAL_ERROR "Original replacement asset metadata is incomplete or unexpected")
endif()
string(JSON builder_revision GET "${manifest_json}" builder source_revision)
string(JSON builder_version GET "${manifest_json}" builder version)
if(NOT builder_revision STREQUAL "91c52b1f4ef3cc8ba3c0638f7536539579af6a9f" OR
   NOT builder_version STREQUAL "10.7")
  message(FATAL_ERROR "Fixture builder pin must remain WLA-DX 10.7 at the reviewed immutable revision")
endif()
string(JSON suite_revision GET "${manifest_json}" suite revision)
string(JSON suite_tree GET "${manifest_json}" suite tree_sha1)
string(JSON builder_tree GET "${manifest_json}" builder source_tree_sha1)
string(JSON builder_archive_sha GET "${manifest_json}" builder git_archive_sha256)
if(NOT suite_revision STREQUAL "31510e12eea6286d36eea060a6adde755e1067aa" OR
   NOT suite_tree STREQUAL "2b8c52424a49a2a7466cf631fd8992c53d0de2fa" OR
   NOT builder_tree STREQUAL "8495d61b96847950e65b1809bf9c7daaccdbd20b" OR
   NOT builder_archive_sha STREQUAL "24a95d77a79feeb70d1de87d66749c006e37337308ce9c00e44efac4c46ab976")
  message(FATAL_ERROR "Mooneye source or WLA-DX source digest does not match the reviewed immutable pin")
endif()

message(STATUS "Verified ${fixture_count} eligible Mooneye ROM(s): ${cpu_count} CPU, ${timer_count} timer (${inventory_status})")
