foreach(required_var IN ITEMS GBB_SIDECAR_FILE GBB_PACKAGE_FILE GBB_EXPECTED_SOURCE_SHA GBB_EXPECTED_RETENTION_DAYS)
  if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
    message(FATAL_ERROR "${required_var} is required")
  endif()
endforeach()

if(NOT EXISTS "${GBB_SIDECAR_FILE}")
  message(FATAL_ERROR "Artifact sidecar is missing: ${GBB_SIDECAR_FILE}")
endif()
if(NOT EXISTS "${GBB_PACKAGE_FILE}")
  message(FATAL_ERROR "Preview package is missing: ${GBB_PACKAGE_FILE}")
endif()
string(LENGTH "${GBB_EXPECTED_SOURCE_SHA}" expected_sha_length)
if(NOT expected_sha_length EQUAL 40 OR NOT GBB_EXPECTED_SOURCE_SHA MATCHES "^[0-9a-fA-F]+$")
  message(FATAL_ERROR "Expected source SHA must be a full 40-character commit ID")
endif()
if(NOT GBB_EXPECTED_RETENTION_DAYS MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "Expected artifact retention must be a positive day count")
endif()

file(READ "${GBB_SIDECAR_FILE}" sidecar_json)
string(JSON sidecar_source_sha ERROR_VARIABLE source_error GET "${sidecar_json}" source_sha)
if(NOT source_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Artifact sidecar has no valid source_sha: ${source_error}")
endif()
if(NOT sidecar_source_sha STREQUAL GBB_EXPECTED_SOURCE_SHA)
  message(FATAL_ERROR "Artifact source SHA mismatch: expected ${GBB_EXPECTED_SOURCE_SHA}, found ${sidecar_source_sha}")
endif()

string(JSON sidecar_package_sha ERROR_VARIABLE package_error GET "${sidecar_json}" package_sha256)
if(NOT package_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Artifact sidecar has no valid package_sha256: ${package_error}")
endif()
string(LENGTH "${sidecar_package_sha}" sidecar_package_sha_length)
if(NOT sidecar_package_sha_length EQUAL 64 OR NOT sidecar_package_sha MATCHES "^[0-9a-fA-F]+$")
  message(FATAL_ERROR "Artifact package SHA-256 must be a full 64-character digest")
endif()
file(SHA256 "${GBB_PACKAGE_FILE}" actual_package_sha)
if(NOT sidecar_package_sha STREQUAL actual_package_sha)
  message(FATAL_ERROR "Artifact package digest mismatch: sidecar ${sidecar_package_sha}, archive ${actual_package_sha}")
endif()

string(JSON sidecar_smoke_result ERROR_VARIABLE smoke_error GET "${sidecar_json}" smoke_result)
if(NOT smoke_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Artifact sidecar has no valid smoke_result: ${smoke_error}")
endif()
if(NOT sidecar_smoke_result STREQUAL "passed")
  message(FATAL_ERROR "Artifact smoke result is not passed: ${sidecar_smoke_result}")
endif()

string(JSON sidecar_retention_days ERROR_VARIABLE retention_error GET "${sidecar_json}" retention_days)
if(NOT retention_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Artifact sidecar has no valid retention_days: ${retention_error}")
endif()
if(NOT sidecar_retention_days STREQUAL GBB_EXPECTED_RETENTION_DAYS)
  message(FATAL_ERROR "Artifact retention mismatch: expected ${GBB_EXPECTED_RETENTION_DAYS} days, found ${sidecar_retention_days}")
endif()

string(JSON sidecar_limits ERROR_VARIABLE limits_error GET "${sidecar_json}" capability_limits)
if(NOT limits_error STREQUAL "NOTFOUND" OR sidecar_limits STREQUAL "")
  message(FATAL_ERROR "Artifact sidecar must declare non-empty capability_limits")
endif()

message(STATUS "Preview artifact sidecar matches ${GBB_EXPECTED_SOURCE_SHA}, package SHA-256, passed smoke, and ${GBB_EXPECTED_RETENTION_DAYS}-day retention")
